### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to betterdiscordbridge

### ISSUE THREAD

**Issue by Akutasan** [Bennyboy1695/BetterDiscordBridge#13]
Full traceback:
```Couldn't pass ProxyInitializeEvent to betterdiscordbridge
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.JDA.getPresence()" because the return value of "io.github.bennyboy1695.betterdiscordbridge.BetterDiscordBridge.getJDA()" is null
	at io.github.bennyboy1695.betterdiscordbridge.BetterDiscordBridge.updateGameStatus(BetterDiscordBridge.java:189) ~[?:?]
	at io.github.bennyboy1695.betterdiscordbridge.BetterDiscordBridge.onProxyInit(BetterDiscordBridge.java:79) ~[?:?]
	at io.github.bennyboy1695.betterdiscordbridge.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity.jar:3.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Maybe because the plugin isn't updated for Velocity 3.0.0?
Hope for a quick fix!

**Comment by FeuerMongoid** [comment]
same problem! pls fix

**Comment by Fjox** [comment]
same problem pls fix

**Comment by wolflord212312** [comment]
Not a issue assuming you guys did not setup correctly And there are many issues with this plugin in newer versions some things need to be changed and fixed

**Comment by wolflord212312** [comment]
But since i plan on using this i will probs update this completely and make a pull request but only if i decide to work on it as i might end up making my own if i find it to much work
