### ISSUE TITLE
Discord chat to minecraft server chat does not work, but works with minecraft 

### ISSUE THREAD

**Issue by X-Niter** [Bennyboy1695/BetterDiscordBridge#4]
Minecraft chat going to discord channel is working just fine, The only part of this that is not working is Discord Chat going to Minecraft servers. 
I am going to try and play with a few things to see if i can fix it. If you happen to be able to sort the issue out before i can. Thank you in advance.
If i manage to figure it out, i will let you know. 

```
[07:51:33] [JDA MainWS-ReadThread/ERROR]: One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: net/kyori/text/serializer/ComponentSerializers
	at io.github.bennyboy1695.betterdiscordbridge.Listeners.DiscordListener.onMessageReceived(DiscordListener.java:23) ~[?:?]
	at JDA.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:409) ~[?:?]
	at JDA.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84) ~[?:?]
	at JDA.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) ~[?:?]
	at JDA.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at JDA.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1069) ~[?:?]
	at JDA.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:929) ~[?:?]
	at JDA.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:908) ~[?:?]
	at JDA.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1101) ~[?:?]
	at dep1.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at dep1.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at dep1.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at dep1.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at dep1.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at dep1.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at dep1.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.text.serializer.ComponentSerializers
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[velocity-proxy-1.0.3-all.jar:1.0.3]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[velocity-proxy-1.0.3-all.jar:1.0.3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212-1-ojdkbuild]
```

**Comment by Bennyboy1695** [comment]
looks like the velocity version your using isn't built correctly as its messing the Text package

**Comment by X-Niter** [comment]
Currently running version 1.0.3. Is your plugin designed for a specific version?

**Comment by Bennyboy1695** [comment]
It wasnt, but it hasnt been updated in a while so i presume velocity has changed the text package. I'll look at why its happening

**Comment by X-Niter** [comment]
Roger. I'll keep tinkering around and see what i can get too.
"(X_Niter#2563)"

**Comment by X-Niter** [comment]
@Bennyboy1695 I'm closing this use sense the pull should fix all of this.
